// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyExpressoScripts.h"
#include "PluginshowcaseGlobalVariables.h"
#include "PluginshowcaseExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UPluginshowcaseMethodsProvider : public UInterface { GENERATED_BODY() };
class IPluginshowcaseMethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class UPluginshowcaseExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UPluginshowcaseGlobalVariables>(GV);
		if(ensure(gv))
		{
			/** Initialize all GV namespace references */
		}
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UPluginshowcaseMethodsProvider::StaticClass();
	}
	
	UObject* GetUserMethodsProviderObject() const
	{
		if(UserMethodsProvider)
			return UserMethodsProvider;
		if(DefaultUserMethodsProvider)
			return DefaultUserMethodsProvider;
		return nullptr;
	}
	
public:
	
	 UPluginshowcaseExpressoScripts() 
	{
	}
};
