// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "PluginshowcaseGlobalVariables.generated.h"

/** Global Articy Variables */
UCLASS(BlueprintType)
class UPluginshowcaseGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	
	 UPluginshowcaseGlobalVariables() 
	{
		/** create the namespaces */
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UPluginshowcaseGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UPluginshowcaseGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
